services:
  postgres:
    container_name: 'grants-db'
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - '5432:5432'
    volumes:
      - pg_volume:/var/lib/postgresql/data
  api:
    container_name: 'grants-api'
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: .
      target: ${NODE_ENV}
    volumes:
      - .:/var/app
      - /var/app/node_modules
    env_file:
      - .env
    command: "npm run start:dev"
    ports:
      - 3000:3000
volumes:
  pg_volume:

